### ISSUE TITLE
Make epistasis optional

### ISSUE THREAD

**Issue by jacobrh91** [ncsa/NCSA-Genomics_EpiQuant_SEMS_Spark#16]
Currently, the SPAEML program automatically creates an RDD with the original SNP values and all of the pairwise (or epistatic) combinations, and then performs the model building process on that RDD.

We need to add in the option to run the model building process on the original SNP values only.

**Comment by sstevenshang** [comment]
I've made the changes. But it seems like that, without epistatic combinations, computation on some small datasets will not terminate. 

For example, when running with the following input:
`src/test/resources/Genotypes/10.Subset.n=300.epiq`
`src/test/resources/Phenotypes/Simulated.Data.1.Reps.Herit.0.92_n=300.epiq`
The program does not terminate.

But with: 
`src/test/resources/Genotypes/10.Subset.n=2648.epiq`
`src/test/resources/Phenotypes/Simulated.Data.1.Reps.Herit.0.92_n=2648.epiq`
The program finished after 4 iterations.

Lowering the threshold also helps to terminate the computation. Not sure if I'm understanding the algorithm incorrectly and thus introducing a bug, or if this is innate to the algorithm.

See the changes here: https://github.com/ncsa/Genomics_EpiQuant/pull/15/commits/1e5643eb8aea18cc9f7ed2546eeaf8c849283b52

**Comment by sstevenshang** [comment]
Problem sort of solved. Turns out, if we run it with the same data either with `spark-submit` or on iForge, it always terminates. Seems to be an issue with my local Spark or Scala. Closed.
